#!/bin/sh

[ -f "/www/luci-static/resources/icons/loading.gif" ] && \
	sed -i "s,/loading.svg,/loading.gif,g" "/www/luci-static/resources/view/limcore/status.js"

uci -q batch <<-EOF >"/dev/null"
	delete firewall.limcore_pre

	delete firewall.limcore_forward
	set firewall.limcore_forward=include
	set firewall.limcore_forward.type=nftables
	set firewall.limcore_forward.path="/var/run/limcore/fw4_forward.nft"
	set firewall.limcore_forward.position="chain-pre"
	set firewall.limcore_forward.chain="forward"

	delete firewall.limcore_input
	set firewall.limcore_input=include
	set firewall.limcore_input.type=nftables
	set firewall.limcore_input.path="/var/run/limcore/fw4_input.nft"
	set firewall.limcore_input.position="chain-pre"
	set firewall.limcore_input.chain="input"

	delete firewall.limcore_post
	set firewall.limcore_post=include
	set firewall.limcore_post.type=nftables
	set firewall.limcore_post.path="/var/run/limcore/fw4_post.nft"
	set firewall.limcore_post.position="table-post"
	commit firewall
EOF

if [ -z "$(uci -q get limcore.config.hwid)" ]; then
	MAC=$(cat /sys/class/net/br-lan/address 2>/dev/null || cat /sys/class/net/eth0/address 2>/dev/null || cat /etc/machine-id 2>/dev/null)
	[ -n "$MAC" ] || MAC="limcore-default-hwid-key"
	HEX=$(echo -n "$MAC" | md5sum | cut -d' ' -f1)
	H1=$(echo "$HEX" | cut -c1-8)
	H2=$(echo "$HEX" | cut -c9-12)
	H3=$(echo "$HEX" | cut -c14-16)
	H4=$(echo "$HEX" | cut -c18-20)
	H5=$(echo "$HEX" | cut -c21-32)
	GEN_HWID="${H1}-${H2}-4${H3}-a${H4}-${H5}"
	uci set limcore.config.hwid="$GEN_HWID"
	uci commit limcore
fi

exit 0
